import { getPlaceholderImage } from '../../utils/placeholderImage'
import sambraniCup1 from '../../assets/products/sambrani-dhoop-cups-1.jpg'
import sambraniCup2 from '../../assets/products/sambrani-dhoop-cups-2.jpg'
import sambraniCup3 from '../../assets/products/sambrani-dhoop-cups-3.jpg'
import chandanCone1 from '../../assets/products/dhoop-cones-1.jpg'
import chandanCone2 from '../../assets/products/dhoop-cones-2.jpg'
import saravanabhavaJar1 from '../../assets/products/saravanabhava-agarbathi-jar-1.jpg'
import sriChakraaAgarbathi1 from '../../assets/products/sri-chakraa-chandan-agarbathi-1.jpg'
import brand19LobanStick1 from '../../assets/products/19-brand-loban-candy-stick-1.jpg'
import sathuragiriKattiSambrani1 from '../../assets/products/sathuragiri-katti-sambrani-1.jpg'
import aalayaaDasangam1 from '../../assets/products/aalayaa-dasangam-plain-cup-1.jpg'
import a1PalSambrani1 from '../../assets/products/a1-pal-sambrani-1.jpg'
import a1PalSambrani2 from '../../assets/products/a1-pal-sambrani-2.jpg'
import jyothiDhunaDhoops1 from '../../assets/products/jyothi-dhuna-dhoops-1.jpg'
import kanthrishtiPowder1 from '../../assets/products/kanthrishti-sambrani-powder-1.jpg'
import singaporeCupSmallSandal1 from '../../assets/products/singapore-cup-sambrani-small-jar-sandal-1.png'
import singaporeCupBigSandal1 from '../../assets/products/singapore-cup-sambrani-big-jar-sandal-1.png'
import singaporeCupBigBlack1 from '../../assets/products/singapore-cup-sambrani-big-jar-black-1.png'
import singaporeCupJumbo1 from '../../assets/products/singapore-cup-sambrani-jumbo-jar-1.png'
import cupSambraniPouchPacking1 from '../../assets/products/cup-sambrani-pouch-packing-sandal-black-1.png'
import pachaKarpooram1 from '../../assets/products/pacha-karpooram-natural-camphor-1.png'

function imagesFor(name) {
  return [
    getPlaceholderImage({ width: 800, height: 800, label: name, tone: 'section' }),
    getPlaceholderImage({ width: 800, height: 800, label: name, tone: 'border' }),
    getPlaceholderImage({ width: 800, height: 800, label: name, tone: 'accent' }),
  ]
}

function product({
  id,
  name,
  slug,
  categoryId,
  fragrance,
  variants,
  ingredients,
  rating,
  ratingCount,
  stock,
  isBestSeller = false,
  isFeatured = false,
  tags = [],
  description,
  images,
}) {
  const prices = variants.map((v) => v.price).filter((p) => typeof p === 'number')
  return {
    id,
    name,
    slug,
    categoryId,
    fragrance,
    variants,
    minPrice: prices.length ? Math.min(...prices) : null,
    maxPrice: prices.length ? Math.max(...prices) : null,
    images: images ?? imagesFor(name),
    rating,
    ratingCount,
    stock,
    isBestSeller,
    isFeatured,
    tags,
    description,
    specifications: {
      Fragrance: fragrance,
      'Available Sizes': variants.map((v) => v.label).join(', '),
      Ingredients: ingredients,
      Stock: stock > 0 ? `${stock} units available` : 'Out of stock',
    },
  }
}

export const products = [
  product({
    id: 'prod-aalayaa-black-cup-sambrani',
    name: 'Aalayaa Black Cup Sambrani',
    slug: 'aalayaa-black-cup-sambrani',
    categoryId: 'cat-sambrani-cups',
    fragrance: 'Loban',
    variants: [{ label: '12 Cups', price: 120 }],
    ingredients: 'Loban fragrance, natural charcoal cup',
    rating: 4.6,
    ratingCount: 132,
    stock: 220,
    isBestSeller: true,
    tags: ['sambrani', 'cup', 'loban'],
    description:
      'Aalayaa Black Cup Sambrani — Loban Fragrance offers a rich, calming aroma that purifies the surroundings and creates a peaceful, spiritual ambiance.',
    images: [sambraniCup3],
  }),
  product({
    id: 'prod-aalayaa-sandal-cup-sambrani',
    name: 'Aalayaa Sandal Cup Sambrani',
    slug: 'aalayaa-sandal-cup-sambrani',
    categoryId: 'cat-sambrani-cups',
    fragrance: 'Sandal',
    variants: [{ label: '12 Cups', price: 120 }],
    ingredients: 'Pure sandalwood fragrance, natural cup',
    rating: 4.7,
    ratingCount: 168,
    stock: 240,
    isBestSeller: true,
    isFeatured: true,
    tags: ['sambrani', 'cup', 'sandal'],
    description:
      'Aalaayaa Sandal Cup Sambrani — Sandal Fragrance fills your space with the soothing, long-lasting aroma of pure sandalwood, creating a calm and divine atmosphere.',
    images: [sambraniCup1, sambraniCup2],
  }),
  product({
    id: 'prod-aalayaa-dasangam-plain-cup',
    name: 'Aalayaa Dasangam Plain Cup',
    slug: 'aalayaa-dasangam-plain-cup',
    categoryId: 'cat-sambrani-cups',
    fragrance: 'Dasangam',
    variants: [{ label: '12 Cups', price: 120 }],
    ingredients: 'Traditional dasangam fragrance blend',
    rating: 4.5,
    ratingCount: 91,
    stock: 180,
    isFeatured: true,
    tags: ['sambrani', 'cup', 'dasangam'],
    description:
      'Aalayaa Dasangam Plain Cup — Experience the pure essence of traditional Dasangam fragrance for a peaceful and spiritually uplifting atmosphere.',
    images: [aalayaaDasangam1],
  }),
  product({
    id: 'prod-a1-pal-sambrani',
    name: 'A1 Pal Sambrani',
    slug: 'a1-pal-sambrani',
    categoryId: 'cat-sambrani-cups',
    fragrance: 'Sambrani',
    variants: [{ label: '10 Cups', price: 120 }],
    ingredients: 'Ven Kungiliyam, Rojanam and traditional aromatic ingredients',
    rating: 4.6,
    ratingCount: 104,
    stock: 160,
    isBestSeller: true,
    tags: ['sambrani', 'cup', 'pal'],
    description: 'A1 Pal Sambrani — Crafted using Ven Kungiliyam, Rojanam and traditional aromatic ingredients for a pure pooja experience.',
    images: [a1PalSambrani1, a1PalSambrani2],
  }),
  product({
    id: 'prod-jyothi-dhuna-dhoops',
    name: 'Jyothi Dhuna Dhoops',
    slug: 'jyothi-dhuna-dhoops',
    categoryId: 'cat-dhuna',
    fragrance: 'Sambrani',
    variants: [
      { label: '30 Gram', price: 30 },
      { label: '50 Gram', price: 50 },
      { label: '100 Gram', price: 100 },
    ],
    ingredients: 'Traditional dhuna blend, natural resin',
    rating: 4.6,
    ratingCount: 187,
    stock: 210,
    isBestSeller: true,
    tags: ['dhuna', 'dhoops'],
    description:
      'Jyothi Dhuna Dhoops fill your space with rich, traditional fragrance, creating a pure, peaceful, and divine atmosphere that is ideal for daily pooja, spiritual rituals, and meditation.',
    images: [jyothiDhunaDhoops1],
  }),
  product({
    id: 'prod-vasudhaa-chandan-cone',
    name: 'Vasudhaa Chandan Cone',
    slug: 'vasudhaa-chandan-cone',
    categoryId: 'cat-dhoop',
    fragrance: 'Chandan',
    variants: [
      { label: '30 Gram', price: 30 },
      { label: '50 Gram', price: 50 },
      { label: '100 Gram', price: 100 },
    ],
    ingredients: 'Pure sandalwood (chandan) essence',
    rating: 4.7,
    ratingCount: 154,
    stock: 200,
    isBestSeller: true,
    tags: ['dhoop', 'cone', 'chandan'],
    description:
      'Vasudhaa Chandan Cones are crafted with the soothing essence of pure sandalwood to create a calm, peaceful and divine atmosphere, making them ideal for daily pooja, meditation, yoga and relaxation with a warm, long-lasting fragrance.',
    images: [chandanCone2, chandanCone1],
  }),
  product({
    id: 'prod-19-brand-loban-candy-stick',
    name: '19 Brand Loban Candy Stick',
    slug: '19-brand-loban-candy-stick',
    categoryId: 'cat-incense',
    fragrance: 'Loban',
    variants: [{ label: '12 Pieces', price: 15, priceUnit: 'per piece' }],
    ingredients: 'Pure loban fragrance, bamboo core',
    rating: 4.5,
    ratingCount: 88,
    stock: 260,
    tags: ['incense', 'loban', 'candy stick'],
    description:
      'Infused with the rich fragrance of pure Loban, 19 Brand Loban Candy Stick creates a peaceful, refreshing atmosphere, perfect for daily pooja, meditation, and home purification.',
    images: [brand19LobanStick1],
  }),
  product({
    id: 'prod-singapore-cup-small-jar-sandal',
    name: 'Singapore Cup Sambrani Small Jar (Sandal Cup)',
    slug: 'singapore-cup-sambrani-small-jar-sandal',
    categoryId: 'cat-sambrani-cups',
    fragrance: 'Sandal',
    variants: [{ label: '30 Pieces', price: 200 }],
    ingredients: 'Thalampoo fragrance, Singapore sambrani filling',
    rating: 4.5,
    ratingCount: 62,
    stock: 130,
    tags: ['sambrani', 'jar', 'sandal'],
    description:
      'Singapore Cup Sambrani Small Jar (Sandal) — Premium Thalampoo fragrance in sandal cup with Singapore sambrani filling for a long-lasting divine aroma.',
    images: [singaporeCupSmallSandal1],
  }),
  product({
    id: 'prod-singapore-cup-big-jar-sandal',
    name: 'Singapore Cup Sambrani Big Jar (Sandal Cup)',
    slug: 'singapore-cup-sambrani-big-jar-sandal',
    categoryId: 'cat-sambrani-cups',
    fragrance: 'Sandal',
    variants: [
      { label: '25 Pieces', price: 250 },
      { label: '30 Pieces', price: 300 },
    ],
    ingredients: 'Thalampoo fragrance, Singapore sambrani filling',
    rating: 4.6,
    ratingCount: 74,
    stock: 110,
    isFeatured: true,
    tags: ['sambrani', 'jar', 'sandal'],
    description:
      'Singapore Cup Sambrani Big Jar (Sandal) — Premium Thalampoo fragrance in sandal cup with Singapore sambrani filling for a long-lasting divine aroma.',
    images: [singaporeCupBigSandal1],
  }),
  product({
    id: 'prod-singapore-cup-big-jar-black',
    name: 'Singapore Cup Sambrani Big Jar (Black Cup)',
    slug: 'singapore-cup-sambrani-big-jar-black',
    categoryId: 'cat-sambrani-cups',
    fragrance: 'Loban',
    variants: [
      { label: '25 Pieces', price: 250 },
      { label: '30 Pieces', price: 300 },
    ],
    ingredients: 'Thalampoo fragrance, Singapore sambrani filling',
    rating: 4.5,
    ratingCount: 69,
    stock: 105,
    tags: ['sambrani', 'jar', 'black'],
    description:
      'Singapore Cup Sambrani Big Jar (Black) — Premium Thalampoo fragrance in black cup with Singapore sambrani filling — long-lasting divine aroma.',
    images: [singaporeCupBigBlack1],
  }),
  product({
    id: 'prod-singapore-cup-jumbo-jar',
    name: 'Singapore Cup Sambrani Jumbo Jar',
    slug: 'singapore-cup-sambrani-jumbo-jar',
    categoryId: 'cat-sambrani-cups',
    fragrance: 'Sambrani',
    variants: [
      { label: '50 Pieces', price: 400 },
      { label: '100 Pieces', price: 800 },
    ],
    ingredients: 'Singapore sambrani filling',
    rating: 4.7,
    ratingCount: 58,
    stock: 90,
    isFeatured: true,
    tags: ['sambrani', 'jar', 'jumbo'],
    description: 'Singapore Cup Sambrani Jumbo Jar — Experience a rich, long-lasting fragrance that creates a peaceful and divine atmosphere every day.',
    images: [singaporeCupJumbo1],
  }),
  product({
    id: 'prod-cup-sambrani-pouch-packing',
    name: 'Cup Sambrani Pouch Packing (Sandal & Black Cup)',
    slug: 'cup-sambrani-pouch-packing-sandal-black',
    categoryId: 'cat-sambrani-cups',
    fragrance: 'Sambrani',
    variants: [
      { label: '10 Pieces', price: null },
      { label: '15 Pieces', price: null },
      { label: '25 Pieces', price: null },
      { label: '30 Pieces', price: null },
      { label: '50 Pieces', price: null },
    ],
    ingredients: 'Sandal fragrance (sandal cup), Loban fragrance (black cup)',
    rating: 4.4,
    ratingCount: 41,
    stock: 140,
    tags: ['sambrani', 'pouch'],
    description:
      'Cup Sambrani Pouch Packing (Sandal and Black) — A perfect blend of Sandal fragrance in the Sandal Cup and Loban fragrance in the Black Cup creates a soothing, long-lasting aroma for daily prayers and a peaceful home.',
    images: [cupSambraniPouchPacking1],
  }),
  product({
    id: 'prod-saravanabhava-agarbathi-jar',
    name: 'Saravanabhava Brand Sambrani Agarbathi Jar',
    slug: 'saravanabhava-brand-sambrani-agarbathi-jar',
    categoryId: 'cat-incense',
    fragrance: 'Sambrani',
    variants: [
      { label: '33 Pieces', price: 100 },
      { label: '42 Pieces', price: 100 },
      { label: '100 Pieces', price: 200 },
    ],
    ingredients: 'Sambrani extract, bamboo core',
    rating: 4.6,
    ratingCount: 121,
    stock: 175,
    isFeatured: true,
    tags: ['incense', 'agarbathi', 'sambrani'],
    description: 'Saravanabhava Brand Sambrani Agarbathi Jar — Experience the authentic aroma of Sambrani with slow-burning incense for everyday worship and meditation.',
    images: [saravanabhavaJar1],
  }),
  product({
    id: 'prod-sri-chakraa-chandan-agarbathi',
    name: 'Sri Chakraa Chandan Agarbathi',
    slug: 'sri-chakraa-chandan-agarbathi',
    categoryId: 'cat-incense',
    fragrance: 'Chandan',
    variants: [
      { label: '20 Gram', price: 25 },
      { label: '32 Gram', price: 35 },
      { label: '50 Gram', price: 60 },
    ],
    ingredients: 'Premium sandalwood (chandan) fragrance, bamboo core',
    rating: 4.7,
    ratingCount: 143,
    stock: 230,
    isFeatured: true,
    tags: ['incense', 'agarbathi', 'chandan'],
    description: 'Sri Chakraa Chandan Agarbathi — A premium sandalwood incense stick with a soothing fragrance, perfect for daily pooja and meditation.',
    images: [sriChakraaAgarbathi1],
  }),
  product({
    id: 'prod-kanthrishti-sambrani-powder',
    name: 'Kanthrishti Sambrani Powder',
    slug: 'kanthrishti-sambrani-powder',
    categoryId: 'cat-powder-resin',
    fragrance: 'Sambrani',
    variants: [
      { label: '30 Gram', price: 30 },
      { label: '50 Gram', price: 50 },
      { label: '100 Gram', price: 100 },
    ],
    ingredients: 'Traditional sambrani powder blend',
    rating: 4.5,
    ratingCount: 84,
    stock: 175,
    tags: ['powder', 'sambrani'],
    description:
      'Kanthrishti Sambrani Powder — Specially formulated to help ward off the evil eye, this traditional sambrani powder fills your space with a pleasant aroma, creating a peaceful and positive atmosphere for your home and workplace.',
    images: [kanthrishtiPowder1],
  }),
  product({
    id: 'prod-sathuragiri-katti-sambrani',
    name: 'Sathuragiri Katti Sambrani',
    slug: 'sathuragiri-katti-sambrani',
    categoryId: 'cat-powder-resin',
    fragrance: 'Sambrani',
    variants: [
      { label: '30 Gram', price: 30 },
      { label: '50 Gram', price: 50 },
      { label: '100 Gram', price: 100 },
    ],
    ingredients: 'Traditional block sambrani resin',
    rating: 4.5,
    ratingCount: 77,
    stock: 165,
    tags: ['resin', 'sambrani', 'katti'],
    description:
      'Sathuragiri Katti Sambrani — Traditional block sambrani that releases a rich, long-lasting fragrance, creating a pure and peaceful atmosphere for daily prayers and spiritual rituals.',
    images: [sathuragiriKattiSambrani1],
  }),
  product({
    id: 'prod-pacha-karpooram',
    name: 'Pacha Karpooram (Natural Camphor)',
    slug: 'pacha-karpooram-natural-camphor',
    categoryId: 'cat-camphor',
    fragrance: 'Camphor',
    variants: [
      { label: '10 Gram', price: 30 },
      { label: '20 Gram', price: 60 },
      { label: '30 Gram', price: 90 },
      { label: '50 Gram', price: 150 },
    ],
    ingredients: '100% pure and natural camphor',
    rating: 4.7,
    ratingCount: 214,
    stock: 320,
    isBestSeller: true,
    tags: ['camphor', 'karpooram'],
    description: 'Pacha Karpooram with a refreshing natural aroma, ideal for pooja, aarthi, and creating a positive, peaceful atmosphere at home.',
    images: [pachaKarpooram1],
  }),
]