export const reviews = [
  {
    id: 'rev1',
    productId: 'prod-aalayaa-black-cup-sambrani',
    userName: 'Anjali Sharma',
    rating: 5,
    comment: 'Beautiful rich loban fragrance — burns evenly and fills the whole house with a calming aroma.',
    createdAt: Date.parse('2026-05-12'),
  },
  {
    id: 'rev2',
    productId: 'prod-aalayaa-black-cup-sambrani',
    userName: 'Ramesh Iyer',
    rating: 4,
    comment: 'Good quality cups, exactly like the ones at our local temple.',
    createdAt: Date.parse('2026-04-28'),
  },
  {
    id: 'rev3',
    productId: 'prod-aalayaa-sandal-cup-sambrani',
    userName: 'Priya Nair',
    rating: 5,
    comment: 'The sandalwood fragrance is soft and long-lasting, not overpowering at all. Perfect for daily pooja.',
    createdAt: Date.parse('2026-05-02'),
  },
  {
    id: 'rev4',
    productId: 'prod-sri-chakraa-chandan-agarbathi',
    userName: 'Vikram Singh',
    rating: 5,
    comment: 'Genuinely premium sandalwood incense sticks — rich and long-lasting. Worth every rupee.',
    createdAt: Date.parse('2026-05-20'),
  },
  {
    id: 'rev5',
    productId: 'prod-jyothi-dhuna-dhoops',
    userName: 'Meera Joshi',
    rating: 5,
    comment: 'Exactly like the dhuna my grandmother used to burn. Very pure and traditional fragrance.',
    createdAt: Date.parse('2026-03-15'),
  },
  {
    id: 'rev6',
    productId: 'prod-jyothi-dhuna-dhoops',
    userName: 'Suresh Patel',
    rating: 4,
    comment: 'Burns cleanly with minimal smoke, and the 100g pack lasts a long time.',
    createdAt: Date.parse('2026-02-27'),
  },
  {
    id: 'rev7',
    productId: 'prod-vasudhaa-chandan-cone',
    userName: 'Lakshmi Rao',
    rating: 5,
    comment: 'Thick cones, deep sandalwood fragrance, and they burn for a good while. My daily aarti essential now.',
    createdAt: Date.parse('2026-05-08'),
  },
  {
    id: 'rev8',
    productId: 'prod-pacha-karpooram',
    userName: 'Anita Desai',
    rating: 5,
    comment: 'Pure camphor, clean burning with no artificial smell. Buy the 50g pack, it lasts a long time.',
    createdAt: Date.parse('2026-05-25'),
  },
  {
    id: 'rev9',
    productId: 'prod-singapore-cup-jumbo-jar',
    userName: 'Karan Mehta',
    rating: 4,
    comment: 'Great value in the jumbo jar — enough sambrani cups to last several months.',
    createdAt: Date.parse('2026-05-18'),
  },
]
