export const reviews = [
  {
    id: 'rev1',
    productId: 'prod-sandal-incense',
    userName: 'Anjali Sharma',
    rating: 5,
    comment: 'Beautifully hand-rolled with a warm, authentic sandalwood fragrance. Burns evenly and lasts long.',
    createdAt: Date.parse('2026-05-12'),
  },
  {
    id: 'rev2',
    productId: 'prod-sandal-incense',
    userName: 'Ramesh Iyer',
    rating: 4,
    comment: 'Lovely fragrance, though I wish the pack had a few more sticks.',
    createdAt: Date.parse('2026-04-28'),
  },
  {
    id: 'rev3',
    productId: 'prod-rose-incense',
    userName: 'Priya Nair',
    rating: 5,
    comment: 'Soft floral scent, not overpowering at all. My whole living room smells wonderful.',
    createdAt: Date.parse('2026-05-02'),
  },
  {
    id: 'rev4',
    productId: 'prod-oudh-incense',
    userName: 'Vikram Singh',
    rating: 5,
    comment: 'Rich and long-lasting — genuinely feels premium. Worth every rupee.',
    createdAt: Date.parse('2026-05-20'),
  },
  {
    id: 'rev5',
    productId: 'prod-loban-dhuna',
    userName: 'Meera Joshi',
    rating: 5,
    comment: 'Exactly like the loban my grandmother used to burn. Very pure and traditional.',
    createdAt: Date.parse('2026-03-15'),
  },
  {
    id: 'rev6',
    productId: 'prod-loban-dhuna',
    userName: 'Suresh Patel',
    rating: 4,
    comment: 'Good quality resin, burns cleanly with minimal smoke.',
    createdAt: Date.parse('2026-02-27'),
  },
  {
    id: 'rev7',
    productId: 'prod-sandal-dhoop',
    userName: 'Lakshmi Rao',
    rating: 5,
    comment: 'Thick sticks, deep fragrance, and they burn for a good while. My daily aarti essential now.',
    createdAt: Date.parse('2026-05-08'),
  },
  {
    id: 'rev8',
    productId: 'prod-festive-gift-set',
    userName: 'Anita Desai',
    rating: 5,
    comment: 'Gifted this to my mother for Diwali — beautifully packaged and every fragrance in the set is lovely.',
    createdAt: Date.parse('2026-05-25'),
  },
  {
    id: 'rev9',
    productId: 'prod-festive-gift-set',
    userName: 'Karan Mehta',
    rating: 4,
    comment: 'Great variety in one box, perfect for gifting during festivals.',
    createdAt: Date.parse('2026-05-18'),
  },
]
